server:
  port: 7070
spring:
  application:
    name: post-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:post-db
    username: post
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
  profiles:
    active: h2